### ISSUE TITLE
How is it possible to remove Weekend days?

### ISSUE THREAD

**Issue by arthursoares** [xdan/datetimepicker#16]
It would be nice to have this option. Only work-days.

**Comment by robertmain** [comment]
It would be nice to be able to remove them from the calendar completely. Is this possible?

**Comment by xdan** [comment]
use remove instead addClass
```
jQuery('#datetimepicker9').datetimepicker({
  onGenerate:function( ct ){
    jQuery(this).find('.xdsoft_date.xdsoft_weekend').remove()
  }
})
```

**Comment by robertmain** [comment]
That nearly works, but now I'm left with the weekday headers remaining...

![image](https://cloud.githubusercontent.com/assets/537684/15207693/ab13b4c2-181f-11e6-8d4a-6bafccf74d45.png)


Is there any possibility of an option being added to completely hide weekends?

**Comment by joaoguilhermels** [comment]
I am using the following code to remove weekends

`
onGenerate: function(ct) {

    $(this).find('.xdsoft_date.xdsoft_weekend').remove();

    $('.xdsoft_calendar table thead tr th').filter(':nth-child(6), :nth-child(7)').remove();

}
`

**Comment by ajithsimon** [comment]
Is it possible to disable only sundays?
