### ISSUE TITLE
xdsoft_weekend is some how set to all days not just weekends

### ISSUE THREAD

**Issue by Timber232** [xdan/datetimepicker#204]
As what the title says, every day is set to as xdsoft_weekend

This bug is causing this solution to break as it disables everything.

```javascript
jQuery('#datetimepicker9').datetimepicker({
  onGenerate:function( ct ){
    jQuery(this).find('.xdsoft_date.xdsoft_weekend')
      .addClass('xdsoft_disabled');
  },
  weekends:['01.01.2014','02.01.2014','03.01.2014','04.01.2014','05.01.2014','06.01.2014'],
  timepicker:false
});
```

**Comment by xdan** [comment]
On default formatDate:	'Y/m/d',
weekends must bi in this format

**Comment by imstanleyyeo** [comment]
So what should be inside 'weekend' say disabling all weekends for month of Jun 2015? Do we need declare formatDate: 'Y.m.d', and list down all the weekend dates?
```
weekends:['2015.06.06','2015.06.07','2015.06.13','2015.06.14','2015.06.20','2015.06.21','2015.06.27','2015.06.28']
```
