### ISSUE TITLE
Can't minify your css because of the missed semicolon

### ISSUE THREAD

**Issue by bafxyz** [xdan/datetimepicker#227]
See file *jquery.datetimepicker.css*

**line 79**

.xdsoft_datetimepicker  .xdsoft_datepicker.active+.xdsoft_timepicker{
	margin-top:8px;
	**margin-bottom:3px**
}

Also please add **jquery.datetimepicker.min.css** into the project

**Comment by wonderchang** [comment]
+1, need the minified one.
