### ISSUE TITLE
Please add Armenian language support

### ISSUE THREAD

**Issue by vgevorgyan** [xdan/datetimepicker#230]
Hello,

Here is the necessary code for adding Armenian language support.

```javascript
hy: { // Armenian
   months: [
      "Հունվար", "Փետրվար", "Մարտ", "Ապրիլ", "Մայիս", "Հունիս", "Հուլիս", "Օգոստոս", "Սեպտեմբեր", "Հոկտեմբեր", "Նոյեմբեր", "Դեկտեմբեր"
   ],
   dayOfWeek: [
      "Կի", "Երկ", "Երք", "Չոր", "Հնգ", "Ուրբ", "Շբթ"
   ]
}
```

Thanks

**Comment by xdan** [comment]
Added. Thank you

07.02.2015, 17:16, "Vardan Gevorgyan" <notifications@github.com>:
> Hello,
>
> Here is the necessary code for adding Armenian language support.
>
> hy: { // Armenian months: [ "Հունվար", "Փետրվար", "Մարտ", "Ապրիլ", "Մայիս", "Հունիս", "Հուլիս", "Օգոստոս", "Սեպտեմբեր", "Հոկտեմբեր", "Նոյեմբեր", "Դեկտեմբեր" ], dayOfWeek: [ "Կի", "Երկ", "Երք", "Չոր", "Հնգ", "Ուրբ", "Շբթ" ] }
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub.

-- 
C уважением,
Чупурнов Валерий
http://xdan.ru
