### ISSUE TITLE
seconds defaulting to current time

### ISSUE THREAD

**Issue by mfrere** [xdan/datetimepicker#246]
I'm using this time format
$('.timeinput').datetimepicker({format:'Y-m-d H:i:s'});

When I pick a time, the seconds default to the *current time's* seconds.
Is this intended? Can I make it default to 00 instead?

I tried to use allowTimes with time strings such as "14:30:00" without success.
Maybe there's already a solution implemented for this use case but I couldn't find any clues in the doc.

**Comment by xdan** [comment]
$('.timeinput').datetimepicker({format:'Y-m-d H:i:00'});

**Comment by mfrere** [comment]
thank you
