### ISSUE TITLE
set date from outside of plugin

### ISSUE THREAD

**Issue by Venzon** [xdan/datetimepicker#248]
Is there any way to set/change date from outside of plugin using jquery or plain js?
for example on click event I want to set current date (new Date())

**Comment by snydesc** [comment]
If you set the value of the input control it will set the date.  

```
$(dtp).val(currentTime);
```

This will not trigger the onChangeEvent though.  Also it will not reformat the text to the default format set when the control was created.  

Another way to do this on an already created datetimepicker is:

```
$(dtp).datetimepicker({value: currentTime});
```
This has the same issue as above where the format is not kept.
If you want the value to be formatted you can modify the plugin's javascript and change the options.value if statement to:
```
if (options.value) 
{
   _xdsoft_datetime.setCurrentTime(options.value);
   if (input && input.val) 
   {
      input.val(_xdsoft_datetime.str);
   }	
}
```

**Comment by Venzon** [comment]
@snydesc thx for reply
