### ISSUE TITLE
JavaScript Error in IE8 - getComputedStyle

### ISSUE THREAD

**Issue by alorp** [xdan/datetimepicker#294]
I got the following error when I downloaded and ran the example code (v2.4.3) in IE8:
Line 1816 - Object doesn't support property or method 'getComputedStyle'

This is error is thrown as IE8 does not support getComputedStyle. As a work around I have added the following JavaScript to my page:

```
if (!window.getComputedStyle) {
    window.getComputedStyle = function(el, pseudo) {
        this.el = el;
        this.getPropertyValue = function(prop) {
            var re = /(\-([a-z]){1})/g;
            if (prop == 'float') prop = 'styleFloat';
            if (re.test(prop)) {
                prop = prop.replace(re, function () {
                    return arguments[2].toUpperCase();
                });
            }
            return el.currentStyle[prop] ? el.currentStyle[prop] : null;
        }
        return this;
    }
}
```

Cam a more permanent solution should be added to the DateTimePicker.

**Comment by sebastiansulinski** [comment]
@alorp - sorry for being so ignorant, but are you seriously still using IE8 ?

**Comment by alorp** [comment]
Unfortunately among some of my corporate client base the use of IE 8 is still very high.
