### ISSUE TITLE
Column of days being highlighted vs just the current date

### ISSUE THREAD

**Issue by She-Codes** [xdan/datetimepicker#295]
If the current day is a Tuesday, all Tuesdays in the month are highlighted vs just the current date.  How would I turn this off to only highlight the current day?
![datetimepicker](https://cloud.githubusercontent.com/assets/5474325/8682388/bfb6c99c-2a3a-11e5-9975-53d81021d49a.png)

**Comment by xdan** [comment]
Can you show me this code case in  https://jsbin.com or another?!

**Comment by She-Codes** [comment]
Sorry this is my first time posting on GitHub I apologize for not linking to an example.

See an example [here](http://codepen.io/she_codes/pen/aOKPZj)

It appears that this only happens when the field is pre-populated with a value....

Thanks

**Comment by xdan** [comment]
If u use moment.js you should redefine formatDate:'MM/DD/YYYY', option too.
http://codepen.io/anon/pen/bdKOPr

**Comment by She-Codes** [comment]
Thank you so much that was definitely it!
