### ISSUE TITLE
Range between dates with plus one day value

### ISSUE THREAD

**Issue by evromalarkey** [xdan/datetimepicker#304]
Hello,

http://xdsoft.net/jqplugins/datetimepicker/#range

I'm trying to accomplish that when I select #date_timepicker_start, the #date_timepicker_end minDate value would change to +1 day of #date_timepicker_start value.

eg. I select 2015/08/18 as start date and the min value on end date would be 2015/08/19

Can anyone help me with this? 

Thanks!

**Comment by akinaru** [comment]
Hello,

Here is the solution :

https://gist.github.com/akinaru/8dd4371db30121204969

```
$(function() {
    
    function checkDateStart()
    {
        if (jQuery('#date_timepicker_start').val()){
          var date = new Date(jQuery('#date_timepicker_start').val());
          date.setDate(date.getDate()+1);
          return date.dateFormat('Y/m/d');
        }
        return false;
    }

    jQuery(function(){
     jQuery('#date_timepicker_start').datetimepicker({
      format:'Y/m/d',
      onShow:function( ct ){
       this.setOptions({
        maxDate:jQuery('#date_timepicker_end').val()?jQuery('#date_timepicker_end').val():false
       })
      },
      timepicker:false
     });

     jQuery('#date_timepicker_end').datetimepicker({
      format:'Y/m/d',
      onShow:function( ct ){
       this.setOptions({
        minDate:checkDateStart()
       })
      },
      timepicker:false
     });

    });
  
});
```

**Comment by evromalarkey** [comment]
Thanks a lot kind sir, that is exactly what I've needed :+1:

**Comment by pakistano** [comment]
Hello,
I created a start and end calendar with http://xdsoft.net/jqplugins/datetimepicker/#range.

I inserted the html and the script inside the contact form 7. This works correctly:

`<script language="javascript" type="text/javascript">
jQuery(function(){
 jQuery('#date_timepicker_start').datetimepicker({ 
  format:'d/m/Y', 
  onShow:function(ct){
   this.setOptions({
    maxDate:jQuery('#date_timepicker_end').val()?jQuery('#date_timepicker_end').val():false,
     formatDate: 'd/m/Y',  
     minDate:'-01/01/1970',
 })
  },
  timepicker:false,
allowTimes:[
  '06:30', '07:00', '07:30', '08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30', '13:00', '13:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00', '21:30', '22:00', '22:30'
 ]
 });
 jQuery('#date_timepicker_end').datetimepicker({
  format:'d/m/Y',
  onShow:function(ct){
   this.setOptions({
    minDate:jQuery('#date_timepicker_start').val()?jQuery('#date_timepicker_start').val():false,
    formatDate: 'd/m/Y',
   })
  },
  timepicker:false,
allowTimes:[
  '06:30', '07:00', '07:30', '08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30', '13:00', '13:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00', '21:30', '22:00', '22:30'
 ]
});
 });
</script>`

WHAT I NEED IS THAT THE END DATE IS SELECTABLE FROM + 3 DAYS FROM THE START DATE. I TESTED THE CODE ABOVE, BUT IT DOESN'T WORK! MAYBE I HAVE TO INSERT LIBRARIES FIRST? HERE->>https://imgur.com/a/Ow0kB1E 

YOU COULD GIVE ME A HAND, I'M GOING MAD
