### ISSUE TITLE
Hide past time

### ISSUE THREAD

**Issue by jkyadav** [xdan/datetimepicker#321]
Is this possible to hide past date? if yes how I can do that?

**Comment by ghanshyamanand** [comment]
$('#datetimepicker').datetimepicker({
    dayOfWeekStart : 1,
    lang:'en',
    minDate: 0,
   minTime:0
  });

**Comment by jkyadav** [comment]
Thanks @ghanshyamanand

**Comment by binfask** [comment]
But how can i active when i changing the date new date?
