### ISSUE TITLE
Unable to get it to work

### ISSUE THREAD

**Issue by JasonTheAdams** [xdan/datetimepicker#342]
Hey! I'm sure I'm doing something stupid, but I just can't find it.

I'm getting no errors in the console. I'm loading jQuery 1.11.3, then the min.js and min.css from [this cdn](https://cdnjs.com/libraries/jquery-datetimepicker). I have an input that I've tried targeting from both the class and selector. When I view the contents of `$('.datetimepicker').datetimepicker();` in the console, it returns the jQuery object with the expected elements, as I would expect it to.

Nothing seems broken... it just does nothing when I click in the input. I'm really puzzled. Any suggestions would be very appreciated.

**Comment by JasonTheAdams** [comment]
I can get it [working here](http://jsfiddle.net/tc2pvbpm/) no problem, though! Bah!

**Comment by sandeepmeenuga** [comment]
Can you help me how to give seconds in the plugin @JasonTheAdams

**Comment by JasonTheAdams** [comment]
@sandeepmeenuga I'd start a new issue as that isn't really relevant to my old issue.
