### ISSUE TITLE
Loacale - Format datetime related issue

### ISSUE THREAD

**Issue by tparmarzc** [xdan/datetimepicker#348]
In my application I need to set locale as per user's culture. I am setting that using below code:

$.datetimepicker.setLocale('' + currentCulture + '');

$("#dateTimePicker").datetimepicker({
inline: false,
format: 'd-M-Y h:i A',
formatTime: 'h:i A',
step: 30
});

Above allows me to select datetime as per locale and format setting. After selecting datetime on blur it is selecting now(). I need to change my jquery.datetimepicker.full.js to keep my selected datetime.

Is that bug or m I missing some setting?

**Comment by orlov0562** [comment]
Hi there, I have faced with same problem.

I have found that when I use EN locale everything works as expected, but in my case with RU locale I also have problem that described above. (One more thing that can affect on this it's my english OS, but I'm not sure )

It looks like the problem in date parser logic, but unfortunately in present time I have not time to fix it in correct way - the parser creation logic is not clear for me from first view ... so I fixed it in rude way - I have replaced localized month's to EN analogue right before parser checks date. After this all works as expected.

To test my solution to your situation you should do next: 

1) Open jquerydatetimepicker.full.js
2) Find next function
```javascript
...
Date.parseDate = function(input, format) {
...
};
...
```
it should be between 2450 - 2470 lines

replace this function with next:
```javascript
...
	Date.parseDate = function(input, format) {
                parseFunctions[format] || createParser(format);

                // -- temp date parsing fix begin --
                var ml = Date.monthNames.map(function(e){return e.substring(0, 3)});
                var mo = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
                for (var i=0; i<mo.length; i++) input = input.replace(ml[i], mo[i]);
                // -- temp date parsing fix end --

                return parseFunctions[format](input);
	};
...
```
Keep in mind that it's very rude fix, so use it on your own risk
