### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by aalvarado** [xdan/datetimepicker#350]
Thanks for a great plugin btw.

I've encountered a use case where I would need to have a user pick a timezone along with the time from the picker.

Is this available in the current plugin or planned?

**Comment by elieteyssedou** [comment]
Yeah, it would be great ! :)

**Comment by ssuess** [comment]
+1

**Comment by badcom** [comment]
+1

**Comment by vedro-compota** [comment]
+1

**Comment by ssuess** [comment]
So does closing this mean "never to be imlemented", "this was a duplicate", or "this was in fact  implemented"?

**Comment by aalvarado** [comment]
it's been 4 years. I don't think it's going to happen
