### ISSUE TITLE
Week numbers are wrong from week 53 2015/2016

### ISSUE THREAD

**Issue by hanfas** [xdan/datetimepicker#351]
The week numbers of "Inline DateTimePicker" are wrong from week 53 2015/16 and forward. Week number 1 is lost. I have deployed datetimepicker live, I should have tested more before, my bad. Now I need fix asap. Help appreciated. Same BUG here: http://xdsoft.net/jqplugins/datetimepicker/  
Suggestions? 
![wrong week numbers](https://cloud.githubusercontent.com/assets/5571793/10784015/ee470e60-7d5b-11e5-84e4-bd71bea8c3f5.PNG)

Found the problem, DateTimePicker does this:
_this.getWeekOfYear = function (datetime) {
var onejan = new Date(datetime.getFullYear(), 0, 1);
return Math.ceil((((datetime - onejan) / 86400000) + onejan.getDay() + 1) / 7);
};
that's not good enough.

We need to distinguish between US week numbers and ISO. 
Something like this.

Date.prototype.getUSWeek = function () {
var onejan = new Date(this.getFullYear(), 0, 1);
return Math.ceil((((this - onejan) / 86400000) + onejan.getDay() + 1) / 7);
}

Date.prototype.getMDay = function () {
return (this.getDay() + 6) % 7;
}
Date.prototype.getISOYear = function () {
var thu = new Date(this.getFullYear(), this.getMonth(), this.getDate() + 3 - this.getMDay());
return thu.getFullYear();
}
Date.prototype.getISOWeek = function () {
var onejan = new Date(this.getISOYear(), 0, 1);
var wk = Math.ceil((((this - onejan) / 86400000) + onejan.getMDay() + 1) / 7);
if (onejan.getMDay() > 3) wk--; return wk;
}

Should be fixed by someone with more insight in DateTimePicker than me.

**Comment by Melhem86** [comment]
same problem

**Comment by Melhem86** [comment]
You can modify getWeekOfYear function to this:

				_this.getWeekOfYear = function (datetime) {
				    datetime = new Date(+datetime);
				    datetime.setHours(0, 0, 0);
				    // Set to nearest Thursday: current date + 4 - current day number
				    // Make Sunday's day number 7
				    datetime.setDate(datetime.getDate() + 4 - (datetime.getDay() || 7));
				    // Get first day of year
				    var yearStart = new Date(datetime.getFullYear(), 0, 1);
				    // Calculate full weeks to nearest Thursday
				    var weekNo = Math.ceil((((datetime - yearStart) / 86400000) + 1) / 7);
				    // Return array of year and week number
				    return weekNo;
				};

**Comment by hanfas** [comment]
Thanks Melhem86,
That seems to take care of the week 53 - week 2 problem, but I think the component should support the standards that exist. The calendar could be used both in the US and in countries that use ISO week numbers. There should be a property or parameter to set firstweekofyearpolicy (firstfullweek/firstweekwithfourdays/etc. These are quite different in the US and other countries. A property like that can decide which of the (two?) major week numbering functions (US and ISO) that should be used.

**Comment by tcmug** [comment]
This is a pretty annoying bug indeed. I'd like to see this alterable in a callback.

**Comment by hanfas** [comment]
Thanks tcmug, this makes it possible to write your own week number handler, and that's helpful if you really know what you are doing. But not really helpful for most programmers, since you should not write your own week number functions when there are standards. I have seen wrongly implemented week number functions for decades now. Wongly implemented functions people paste from the internet, causing confusion and aggrevation among users, long after deployment. These week number bugs can creep up on you any January 1st in the future or back in time. You, the programmer simply "forgot" to test them all, and frankly it's a daunting task to test your own week number functions agains the couple of different numbering systems that exist. It's not that difficult, there are standards - and a great calendar should have it built in. If I can be of any help, let me know - and sorry, I don't know how github works.

**Comment by tcmug** [comment]
I agree that this definitely needs to be a setting, but I'm lacking the knowledge of week number calculations around the world :) If we could at least add the US and EU week numbers there as a setting it would be a great start.

As for how github works: https://guides.github.com/activities/contributing-to-open-source/
