### ISSUE TITLE
onClose function works twice

### ISSUE THREAD

**Issue by Ivan-Feofanov** [xdan/datetimepicker#363]
I found that onClick function wotks twice - first time when datetime picker close, second time when input field lost focus.

**Comment by davincho** [comment]
Any updates on that? I have got the same issue that `onClose` is called twice.

**Comment by kamalezz** [comment]
Any updates on this one?
Initially when I set the value and click done, everything is fine.
Once I try to edit the value, I click done and it calls onClose, while keeping the new value (Which is great).
Now on any other mouse click anywhere on the page, the OnClose is called again and it reverts the value back to what it was before the edit.
Any help would be highly appreciated.
