### ISSUE TITLE
issue while rendering in modal

### ISSUE THREAD

**Issue by ashish-joshi-nct** [xdan/datetimepicker#400]
#I have issue with this plugin to show in inline mode when i open bootstrap modal..

`
 <div class="modal fade" id="availability_modal" role="dialog"> 
    <div class="modal-dialog"> 
         
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    &times;
                </button>
                <h4 class="modal-title">View availability of %SUPP_NAME%</h4>
            </div>
            <div class="modal-body">
                <div id="availability_calender"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    Close
                </button>
            </div>
        </div>
    </div>
 </div> 
 `

below code is used to render it.

` 
  $(document).on("click","#open_availability",function(e){
         setTimeout(function(){
             jQuery('#availability_calender').datetimepicker({
              formatDate: "d.m.Y", 
              inline:true,
              timepicker:false,
              highlightedDates: [
                 "29.02.2016,Meeting with Pete", 
                 "24.02.2016,Christmas Eve,xdsoft_highlighted_mint", 
                 "25.02.2016,Christmas Day,xdsoft_highlighted_mint", 
                 "26.02.2016,Thanksgiving"
              ],
              highlightedPeriods: [
                 "27.04.2015,08.05.2015,Business trip", 
                 "11.07.2015,31.08.2015,Summer holiday 2015,xdsoft_highlighted_mint", 
                 "21.12.2015,01.01.2016,Christmas holiday 2015"
              ]
             });
         },1000);
     });`

it works fine when i don't use it in modal..
any help is appreciated..

**Comment by mandadimuralidharreddy** [comment]
Did you get any solution for this problem.
