### ISSUE TITLE
$(...).datetimepicker is not a function

### ISSUE THREAD

**Issue by jamesaspence** [xdan/datetimepicker#412]
Hi,

I'm loading in both jQuery and jquery-datetimepicker through npm as such:

```
// Foundation seems to misbehave if we don't do it this way.
window.$ = window.jQuery = require('jquery');

var datetimepicker = require('jquery-datetimepicker');
```

Then, in our `document.ready()`:

```
$('#datetimepicker').datetimepicker({
    format:'MM-DD-YYYY h:mm a',
    formatTime:'h:mm a',
    formatDate:'DD.MM.YYYY'
});
```

However, this call gives us the error `$(...).datetimepicker is not a function`.

What am I doing wrong? This was working fine no more than a week ago, I ran an `npm install` and I think it must've updated the datetimepicker, because now it's failing.

For reference, I'm using jQuery 2.1.4, and jquery-datetimepicker is 2.5.1.

**Comment by jamesaspence** [comment]
Seems very similar to this other issue:

https://github.com/xdan/datetimepicker/issues/396

**Comment by jamesaspence** [comment]
bump? Any word on this?

**Comment by ConstantinChirila** [comment]
You guys copied the wrong code. Go into the build folder and grab the jquery.datetimepicker.full.js
It should fix it! :)

**Comment by hanachin** [comment]
It seems fixed in https://github.com/xdan/datetimepicker/pull/399

**Comment by WilliamMayor** [comment]
This caused me quite the headache this evening.

I'm trying to use node.js with browserify to define all my JS dependencies and package everything up into one file. I couldn't get this to work for this library. I always got the `$(...).datetimepicker is not a function` error. No matter which of the JS files in the repo I tried to `require`.

Looking over the `jquery.datetimepicker.full.js` file it looks like `jquery.mousewheel` is concatenated to the end of the file. This (I think) causes the `module.exports` to reference the mousewheel factory, not the datetimepicker factory.

I've got this working by separating the `php-date-formatter`, `jquery.mousewheel`, and `jquery.datetimepicker` into separate files in my code base (so they're not installed via `npm` anymore). I then had to modify the `php-date-formatter.js` by adding `module.exports=DateFormatter` to the end of the file.

So now when I need to use the date time picker I have this:

    var $ = require('jquery');
    window.DateFormatter = require("../vendor/php-date-formatter");
    require("../vendor/mousewheel")($);
    require("../vendor/datetimepicker")($);

I'm not really a node.js guy so if there's a better way to do any of this, I'd be grateful for the advice.

**Comment by wankdanker** [comment]
@WilliamMayor I agree with your analysis. There is a branch of `php-date-formatter` which has a commonjs, amd and browser export header (https://github.com/kartik-v/php-date-formatter/tree/closure). I was able to keep my dependencies managed by npm by doing the following:

installing...

```sh
npm install jquery-datetimepicker
npm install https://github.com/kartik-v/php-date-formatter.git#closure
```

included in code...

```js
DateFormatter = require('php-date-formatter')($);
require('jquery-mousewheel/jquery.mousewheel.js')($);
require('jquery-datetimepicker/jquery.datetimepicker.js')($);
```

Hope this helps someone save some time.

**Comment by fsavina** [comment]
I had the same problem, I've solved it loading datetimepicker via the [scripts loader](https://www.npmjs.com/package/script-loader).

First of all, install the package:
`npm install --save-dev script-loader`

and require datetimepicker as following:
`require('script!jquery-datetimepicker');`

Hope this is helpful.
