### ISSUE TITLE
options.mask.replace is not a function

### ISSUE THREAD

**Issue by suhaotian** [xdan/datetimepicker#414]
jquery.datetimepicker.full.js:1743 Uncaught TypeError: options.mask.replace is not a function

**Comment by vdeapps** [comment]
I have the same error in Internet Explorer.
To fix it, use 0 or 1 against true or false value.
{mask: 0}

In the source code all value are set with 0 or 1, not true or false. !!!!

**Comment by Sibz** [comment]
Setting mask to true, gets rid of the error for me, if its false I get above error. However I don't want the mask.

**Comment by suhaotian** [comment]
:+1:

**Comment by RahamSher** [comment]
Dears,I have the same problem,how to fix it.

**Comment by Sibz** [comment]
@RahamSher Yes that's right.
People can re-download the jquery.datetimepicker.js from the root of this repository as it has been fixed (as per PR #417)
