### ISSUE TITLE
Disabling past time - current time is also disabled

### ISSUE THREAD

**Issue by deepika1203** [xdan/datetimepicker#424]
I have used `minDateTime` to disable the past date and time. The past date and time are disabled correctly. But it is disabling current time also.

For example, If the current time is 17:15 Hrs, then 17:00 is disabled in the time picker
Is there any solution for this?

This is my code,

    $("#timePkr").datetimepicker({
        minDate: 0,
        minDateTime: new Date(),
        todayButton: true,
        closeOnWithoutClick: true,
        scrollInput: false,
        closeOnDateTimeSelect: true,
     });

**Comment by Sibz** [comment]
As far I can understand, the minDateTime is functioning correctly, but you still want to be able to set the current hour if the actual time for the current hour has past.

In this case I would subtract an hour (or portion of) from the current date/time.

```javascript
var minDateTime =  new Date();
minDateTime.setHours(minDateTime.getHours-1);
$("#timePkr").datetimepicker({
    minDate: 0,
    minDateTime: minDateTime,
    todayButton: true,
    closeOnWithoutClick: true,
    scrollInput: false,
    closeOnDateTimeSelect: true,
 });
```

**Comment by deepika1203** [comment]
Thank you so much for your response. The above code lets me to select the current hour. But the current hour is not highlighted. If the current hour is 15:45, then 16:00 is highlighted by default. But I want 15:00 to be highlighted. Is there any way to do this?

**Comment by Sibz** [comment]
Yes. I believe setting the defaultTime should do the trick.
```javascript
var minDateTime =  new Date();
minDateTime.setHours(minDateTime.getHours()-1);
$("#timePkr").datetimepicker({
    minDate: 0,
    minDateTime: minDateTime,
    todayButton: true,
    closeOnWithoutClick: true,
    scrollInput: false,
    closeOnDateTimeSelect: true,
    defaultTime: minDateTime
 });
```

**Comment by deepika1203** [comment]
Thanks a lot for this trick.. It works perfectly fine..!
