### ISSUE TITLE
I recreated the arrows for Hi-DPI displays

### ISSUE THREAD

**Issue by NetOperatorWibby** [xdan/datetimepicker#445]
Seeing as how pull requests have been sitting in limbo since last year, I figured I'd just create a new issue with the asset attached.
#### Image

![dtp](https://cloud.githubusercontent.com/assets/1288356/14875576/fe9c84e4-0cd9-11e6-87d1-a2a7ee8b915d.png)
#### Changed Code

```
.xdsoft_datetimepicker .xdsoft_label i,
.xdsoft_datetimepicker .xdsoft_prev,
.xdsoft_datetimepicker .xdsoft_next,
.xdsoft_datetimepicker .xdsoft_today_button {
  background-image: url("../images/plugins/dtp.png");
  background-size: 100px 30px;
}

.xdsoft_datetimepicker.xdsoft_dark .xdsoft_label i,
.xdsoft_datetimepicker.xdsoft_dark .xdsoft_prev,
.xdsoft_datetimepicker.xdsoft_dark .xdsoft_next,
.xdsoft_datetimepicker.xdsoft_dark .xdsoft_today_button {
  background-image: url("../images/plugins/dtp.png");
  background-size: 100px 30px;
}
```

Of course, you'd update `background-image` to wherever you decide to place the new image.

**Comment by yairEO** [comment]
It shouldn't be images anyway, that is so 2005. use unicode when possible and resort to icon font when possible, and last result should be SVG images. never **ever** png files... that is the worst.

http://www.copypastecharacter.com

**Comment by NetOperatorWibby** [comment]
Icon fonts are never the answer. If anything, SVG is the proper way to go, but my optimized PNG works too.

—
NetOperator Wibby
Purveyor of Awesome

    _____________________________
