### ISSUE TITLE
Low perfomance in old IE

### ISSUE THREAD

**Issue by faiwer** [xdan/datetimepicker#461]
```js
options = ($.isPlainObject(opt) || !opt) ? $.extend(true, {}, default_options, opt) : $.extend(true, {}, default_options),
```
this code used deep `$.extend`. If also used `es5-sham` & `babel-polifill` loading 1 calendar instance in lazy mode can take from 400ms to 40sec.

### russian

В общем посчастливилось мне поддерживать IE8 в проекте, где используется `lodash`. 4-ая версия оного потребовала `es5-shim` и... и блин `es5-sham`, что куда хуже. Он же, падла, потребовался и `babel-polifill`-у (использую `es2015`). Т.е. это приводит к тому, что `IE8` начинает уметь многое из `es5` в полной мере, и часть через одно место. Одна из проблем появилась с вашим календарём. Он может грузиться как пол секунды на инстанс в lazy-моде, так и секунд 40 к ряду. Зависит от расположения Марса, как обычно, не иначе.

Мне удалось определить что именно тормозит. DOM исключил, т.к. lazy-mode. Оказалось что люто тормозит именно `$.extend`, т.к. вы используете `deep`. Вызывается оно пару сотен раз к ряду (с учётом рекурсии). А почему? А потому что там происходит копирование ВСЕЙ локализации, которая в build-е присутствует вся целиком. Ну т.е. это здоровенный такой hash-объект со всеми переводами и не только. Несчастный 8-й ослик надрывается до изнемогания.

В общем ситуация специфическая. Багом не является. Создал `issue` просто, чтобы вы были в курсе такой проблемы. `deep` `$.extend` таких объектов в старых браузерах может быть невыносимо долгим. Возможно к этому ещё как-то приложили руки `es5-sh[am|im]`, реализуя такие интерфейсы как `isArray`, и, что хуже, такие как `getPrototypeOf`.

Страница же с примерами в ie8 грузится более-менее нормально. Так что не факт, что нужно что-нибудь менять.

**Comment by xdan** [comment]
Theoretically, you can reset $.fn.datetimepicker.defaults.i18n = {ru:{...}};
russian
Благодарю богов что мне с этим дело иметь не приходится уже несколько лет
