### ISSUE TITLE
PM times being changed to AM

### ISSUE THREAD

**Issue by mrberggg** [xdan/datetimepicker#495]
When using format 'n/j/Y g:ia', with no space between the minutes and the am/pm, pm times are being converted to am on input blur. If I change the format to 'n/j/Y g:i a' the bug no longer occurs.

**Comment by billzhong** [comment]
I think it is a bug related to https://github.com/kartik-v/php-date-formatter
You can use MomentJS to replace it: http://xdsoft.net/jqplugins/datetimepicker/#use_other_date_parser

**Comment by mrberggg** [comment]
@billzhong thanks, that solved the issue for me. If php-date-formatter doesn't work properly, can I suggest moving the default to moment?

**Comment by billzhong** [comment]
@mrberggg It is up to the author :)
