### ISSUE TITLE
Enable/disable scrolling in calendar

### ISSUE THREAD

**Issue by alpha-ninja** [xdan/datetimepicker#5]
Hey,

I would like to have support for enabling and disabling scrolling in the calendar to change months through the `default_options` variable.

Thanks!

**Comment by fr0z3nfyr** [comment]
@xdan Thanks for the wonderful plugin.

It would be great to have this info included in docs in detail.

**Comment by TwentyOneSolutions** [comment]
`scrollInput: false` should be the default IMO.

Thank you for the plugin.

**Comment by Veepim** [comment]
This plugin is very useful

**Comment by isapir** [comment]
@Veepim  It used to be much more useful.  HTML5 added new input types.  See https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_datetime-local

**Comment by hxy2193** [comment]
我想去除滚动改变时间的效果,请问在哪里添加crollMonth：true，
scrollTime：true，
scrollInput：true，这些东西呢?

**Comment by heshengbang** [comment]
直接用jquery包装的输入框对象去调用datetimepicker构造方法，它的参数是一个键值对象，在里面指定scrollInput: false即可。
