### ISSUE TITLE
Plugin does not work for dynamically created element

### ISSUE THREAD

**Issue by cmanish049** [xdan/datetimepicker#514]
I tried to implement this plugin on dynamically created element but it doesnot work.
Below is my code
`$('#optional-param-container').html('<label>From Date</label><input class="form-control" id="from-date" type="text" name="param1"><label>To Date</label><input class="form-control" id="to-date" type="text" name="param2">');
              $('#from-date').datetimepicker({
                  timepicker:false,
                  formatDate:'Y-m-d',
                  format:'Y-m-d',
              });
              $('#to-date').datetimepicker({
                  timepicker:false,
                  formatDate:'Y-m-d',
                  format:'Y-m-d',
              });`

**Comment by droomdre** [comment]
it works. I had the same issue. U just have to initialize the datetimepicker after ur dynamically created content.
May be just made an init function:
```
function init(){
             jQuery.datetimepicker.setLocale('de');
             jQuery('#field_start_time').datetimepicker({
...
}
```
and call init() again after ur content.
