### ISSUE TITLE
Cannot read property 'formatDate' of null

### ISSUE THREAD

**Issue by Palkan-Karabov** [xdan/datetimepicker#573]
`<input type="text" class="uk-input datetimepicker" name="Reminder[dateReminder]" placeholder="Date Reminder">`
`<script>
	$(document).ready(function(){
		$('.datetimepicker').datetimepicker();
	})
</script>`
Uncaught TypeError: Cannot read property 'formatDate' of null
    at jquery.datetimepicker.js:1635

**Comment by andrefarzat** [comment]
Was it solved ?

**Comment by andrefarzat** [comment]
ok, I looks like I solved it here. It is necessary to inform the dateFormatter (here I am using [moment](momentjs.com) )

```js
$.datetimepicker.setDateFormatter({
    parseDate: function (date, format) {
        var d = moment(date, format);
        return d.isValid() ? d.toDate() : false;
    },
    formatDate: function (date, format) {
        return moment(date).format(format);
    },
});

**Comment by decoursin** [comment]
Yeah, I'm having the same problem, including the ```$.datetimepicker.setDateFormatter({..})``` seems like the only way to fix it, which doesn't really make sense. I shouldn't have to include a parseDate or formatDate function. I'm not passing a `moment` date, I'm just passing normal strings. Heck I've tried a JS Date object too, this also didn't work. Maybe it's a bug

**Comment by sunnygapbit** [comment]
Guys use this code 
$.datetimepicker.setDateFormatter('moment');
This code is working for me

**Comment by JuJoGuAl** [comment]
> Guys use this code
> $.datetimepicker.setDateFormatter('moment');
> This code is working for me

Work for me!

**Comment by rohangoyal18** [comment]
> Guys use this code
> $.datetimepicker.setDateFormatter('moment');
> This code is working for me

this also worked for me @sunnygabpit thanku and cheers
