### ISSUE TITLE
Bower removal BC

### ISSUE THREAD

**Issue by tchiotludo** [xdan/datetimepicker#606]
You have removed bower.json  :
https://github.com/xdan/datetimepicker/commit/b7dc5fe1d39cb1bd82b526613837fd2df80bcf47

You may have done a version gap since it's a breaking change.
For myself, it break the whole continous integration of all my projet, since it depend from your package.

**Comment by FME-Daniel** [comment]
https://github.com/xdan/datetimepicker/issues/607 is also a victim of today's changes. Linking here as reference.
