### ISSUE TITLE
MASK is only possible on value and not in placeholder

### ISSUE THREAD

**Issue by cfasol** [xdan/datetimepicker#616]
the mask value is put only on input value attribute.
it is not possible configure attribute field where apply mask like to placeholder or value attribute ecc

**Comment by Mator62** [comment]
+1 
After apply mask the value of field disappear...
It's very problematic for edit form !!!

Please Help !

**Comment by cfasol** [comment]
I develop this fix but i do not pushed it

**Comment by Mator62** [comment]
Can you please push your patch ? Or give the solution ?

**Comment by cfasol** [comment]
when came back to home I push all
