### ISSUE TITLE
Selecting year or months from datepicker throw exception

### ISSUE THREAD

**Issue by romero83** [xdan/datetimepicker#636]
Hi!

I use the latest version: 2.5.17
When I try to select different year or month from datepicker selection fields it throws an exception:

_In Chrome:_
**Uncaught TypeError: Cannot read property '0' of undefined**  at event.originalEvent.touches[0]
_In Firexox:_
**TypeError: event.originalEvent.touches is undefined**

```
month_picker.find('.xdsoft_select')
	.xdsoftScroller(options)
	.on('touchstart mousedown.xdsoft', function (event) {
		this.touchMoved = false;
		this.touchStartPosition = event.originalEvent.touches[0]
		event.stopPropagation();
		event.preventDefault();
	})
```
Browser: Desktop Chrome ver. 63 or Desktop Firefox ver. 57

**Comment by sebros80** [comment]
I have the same issue on IE11

**Comment by Snake231088** [comment]
Same issue with Chrome and Firefox on macOS

**Comment by danielieb** [comment]
Same error here

**Comment by kevindb** [comment]
I'm having the same issue.

Chrome 65 on macOS
jQuery: v3.3.1
datetimepicker: v2.5.18

It looks like it's a problem with `event.originalEvent.touches[0]` on [line 1077](https://github.com/xdan/datetimepicker/blame/master/jquery.datetimepicker.js#L1077) in the source file. That line introduced some new 'touch' functionality in commit [a486c92 Improve sensitivity of scrollable select boxes on mobile](https://github.com/xdan/datetimepicker/commit/a486c92379e6b4151cf7b7362729d319516c56b1).

Here is a JSFiddle example: https://jsfiddle.net/kevindb/j256h2rt/
Simply click in the field and try choosing a different month from the dropdown.

I'm sorry, I don't know enough about how datetimepicker uses touch events to submit a pull request. I'm sure you don't want to simply remove the line.

P.S. I created a [JSFiddle using 2.5.14](https://jsfiddle.net/kevindb/bt0u09bc/), and this error does not present.
