### ISSUE TITLE
use datetimepicker with angular

### ISSUE THREAD

**Issue by gayabell** [xdan/datetimepicker#651]
I am trying to use this library in my project with angular, but don't know how to make it run, do'es any one did it before, do you have any example, here is my code : 
in my component :
`
import { Component, OnInit } from '@angular/core';
import * as $ from 'jquery';
import datetimepicker from 'jquery-datetimepicker';

@Component({
  selector: 'c1',
  templateUrl: './c1.component.html',
  styleUrls: ['./c1.component.css']
})
export class C1Component implements OnInit {

  title = 'Look jQuery Animation working in action!';

  constructor() { }

  public ngOnInit() {
    $(document).ready(function(){
        $('#datetimepicker_mask').datetimepicker({
         timepicker:false,
         mask:true,
        });
    });
  }
}
`

html template : 
`<input id="datetimepicker_mask" type="text" >`

.angular-cli.json
`
"styles": [
        "../node_modules/jquery-datetimepicker/build/jquery.datetimepicker.min.css",
        "styles.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/jquery-datetimepicker/build/jquery.datetimepicker.full.js"
      ],
`

**Comment by gayabell** [comment]
by replacing "import datetimepicker from 'jquery-datetimepicker';" with import 'jquery-datetimepicker';
this code works perfectly.

**Comment by niraj-ui** [comment]
i am doing same but not work
