### ISSUE TITLE
Get UTC/GMT time

### ISSUE THREAD

**Issue by josephernest** [xdan/datetimepicker#653]
I use:

    var currentDate = new Date(new Date().getTime() + 24 * 60 * 60 * 1000);
    var day = currentDate.getDate(); var month = currentDate.getMonth() + 1; var year = currentDate.getFullYear(); var startDate = year + '/' + month + '/' + day;

    $('#when').datetimepicker({dayOfWeekStart : 1, lang: 'fr', step: 30, defaultDate: startDate, defaultTime: '12:00', beforeShowDay: function(date) { if (date - new Date().setHours(0,0,0,0) < 0) { return [false, ""] }; return [true, ""]; }});
    $('#when').datetimepicker({format:'l d F Y à H:i'});

    # Example: mardi 13 mars 2018 à 15:00

How is it possible to make that
    
    $('#when').val();

returns the same datetime  but in UTC / GMT (instead of local timezone, which is GMT+2), or UNIX timestamp?

**Comment by JamesWatling** [comment]
@josephernest I think you were meant to be tagged instead 😄

**Comment by josephernest** [comment]
@tunnes Yes but 

    $('#your-selector').datetimepicker('getValue')
    // returns -> Fri Apr 20 2018 00:00:00 GMT-0300 (-03)

doesn't return UTC/GMT time, it returns local-timezone time (here GTM-3).

How to get UTC (GMT+0) timezone instead?

**Comment by tunnes** [comment]
@josephernest You're right! My bad sorry, but did you try to convert the date?
```js
let date = new Date( $('#your-selector').datetimepicker('getValue') );
date.toUTCString();
// returns -> Fri, 20 Apr 2018 03:00:00 GMT
```

**Comment by josephernest** [comment]
Thanks @tunnes, you're right, since it's a Javascript Date object, we can use the standard Javascript methods.
