### ISSUE TITLE
Scroll speed toooo fast

### ISSUE THREAD

**Issue by dmcanaveral** [xdan/datetimepicker#689]
I saw issue [179](https://github.com/xdan/datetimepicker/issues/179) about scroll speed and that it was fixed in 2.3.8 but the [demo page](https://xdsoft.net/jqplugins/datetimepicker/) is still scrolling really fast on the Mac magic mouse to the point where it's annoying because you have to scroll so slow to not go too far. Is there anything that can be done to slow it down? Thanks in advance.

**Comment by jaypatel512** [comment]
Ran into the same problem here. Any way to reduce the speed ?

**Comment by dmcanaveral** [comment]
@jaypatel512 I haven't figured anything out yet, I just disabled the scroll for the months by setting scrollMonth to false

**Comment by mohammedkhan** [comment]
Hi. This looks to still be a problem in version 2.5.20, could the issue fixed in #723 have possibly regressed somehow?
