### ISSUE TITLE
Hours , Minutes dropdowns are scrolling the wrong way

### ISSUE THREAD

**Issue by jasjitCheema** [xdan/datetimepicker#763]
Hello 
Hours , Minutes dropdowns are scrolling the opposite of Mouse scroll. Am i some thing wrong or there is some issue in it

**Comment by surya04pratap** [comment]
I'm also facing this issue.

**Comment by 1candido** [comment]
the _**Merge pull request #723 from toptalo/issue-689**_ introduced this problem. I solved it by downloading a commit before.

**Comment by TabeaW** [comment]
Try in line 809 of jquery.datetimepicker.full.js ```if ('deltaY' in e) { deltaY = -e.deltaY; }```instead of ```if ('deltaY' in e) { deltaY = -e.deltaY; }```. This solved the issue for me.
