### ISSUE TITLE
Feature request: Display only year and month, not days

### ISSUE THREAD

**Issue by awthird** [xdan/datetimepicker#771]
It would be very handy if setting the format or dateFormat to 'Y-m' would disable the display of the days or, alternatively, there were options to hide the days in the displayed calendar. Currently, it shows the days with all of them selected, which implies a daily granularity. For some purposes, that can be misleading or redundant.

Thanks.

**Comment by arcanemachine** [comment]
Had the same issue. Add this to your datetimepicker constructor:

```
onGenerate() {
  const pickerEl = this[0];

    // hide the datepicker for this element, but keep the month selector
    pickerEl.querySelector(".xdsoft_calendar").classList.add("d-none");

    // fix widget styles
    pickerEl.classList.add("my-2", "py-0");
}

```

**Comment by awthird** [comment]
Thanks for the suggestion. Unfortunately, it doesn't work for me - the calendar days for the selected year/month are still displayed.  Here's my constructor:

```
$("#datepicker").datetimepicker({
     onGenerate:function( ct ){
       const pickerEl = this[0];

       // hide the datepicker for this element, but keep the month selector
       pickerEl.querySelector(".xdsoft_calendar").classList.add("d-none");

       // fix widget styles
       pickerEl.classList.add("my-2", "py-0");
     },
     closeOnWithoutClick: true,
     format: 'Y-m',
     formatDate: 'Y-m',
   });
```

Anyway, maybe it's not quite as simple as I originally thought. I note that one has to click on a day in the displayed days part of the calendar to trigger the update, even if only selecting the year and month, so hiding the calendar days would make that impossible.

**Comment by arcanemachine** [comment]
I apologize for the issue, my first comment was using Bootstrap classes in the example, which would probably need to be swapped for other style rules. I edited the comment to provide a sample.

Regarding your last paragraph, you can override the `onChangeMonth` method to handle changes in the year/month pickers without requiring the day itself to be clicked. I created a handler function for this purpose, which assigned to handle both `onChangeMonth` and `onSelectDate` (all this is done in the constructor).

This is all available in the [docs](https://xdsoft.net/jqplugins/datetimepicker/) although I will admit that I had to mess around a lot to get things working the way I wanted them. But what you want to achieve (which appears to have a lot of overlap with what I wanted to achieve) should be doable.
